typography_spectrum: 0.85129
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.4913334387820214
  lightness: 0.8149749101139605
  saturation: 0.07895187987014651
  rhythmicContrast: 0.6742397660855204
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
name: maps
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Zebadiah K. Steeby
purpose: []
